// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2020  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================

/**
 * This class was generated using exec.php
 * against an XML schema provided by Kaltura.
 * 
 * MANUAL CHANGES TO THIS CLASS WILL BE OVERWRITTEN.
 */

open class GenerateMetadataBySubtitlesJob: ObjectBase {

	public class GenerateMetadataBySubtitlesJobTokenizer: ObjectBase.ObjectBaseTokenizer {
		
		public var id: BaseTokenizedObject {
			get {
				return self.append("id") 
			}
		}
		
		public var createDate: BaseTokenizedObject {
			get {
				return self.append("createDate") 
			}
		}
		
		public var updateDate: BaseTokenizedObject {
			get {
				return self.append("updateDate") 
			}
		}
		
		public var fileName: BaseTokenizedObject {
			get {
				return self.append("fileName") 
			}
		}
		
		public var status: BaseTokenizedObject {
			get {
				return self.append("status") 
			}
		}
		
		public var errorMessage: BaseTokenizedObject {
			get {
				return self.append("errorMessage") 
			}
		}
	}

	/**  a Long type generated by the subtitles service and provides a unique identifier
	  for the object,              together with a metadataGenerationJob prefix which
	  is added by the aiMetadataGenerator service.              TODO: WHAT DOES IT
	  MEAN?  */
	public var id: Int64? = nil
	/**  an Integer type representing the EPOCH time in seconds that the object was
	  created.  */
	public var createDate: Int64? = nil
	/**  an Integer type representing the EPOCH time in seconds that the object was last
	  updated.  */
	public var updateDate: Int64? = nil
	/**  a String type listing the file name that was uploaded.  */
	public var fileName: String? = nil
	/**  can be either Processing/Success/Failed, per the last status updated by the
	  aiMetadataGenerator micro-service.  */
	public var status: GenerateMetadataStatus? = nil
	/**  an optional String describing the error found in case that the Status is set to
	  Failed.  */
	public var errorMessage: String? = nil


	public func setMultiRequestToken(id: String) {
		self.dict["id"] = id
	}
	
	public func setMultiRequestToken(createDate: String) {
		self.dict["createDate"] = createDate
	}
	
	public func setMultiRequestToken(updateDate: String) {
		self.dict["updateDate"] = updateDate
	}
	
	public func setMultiRequestToken(fileName: String) {
		self.dict["fileName"] = fileName
	}
	
	public func setMultiRequestToken(status: String) {
		self.dict["status"] = status
	}
	
	public func setMultiRequestToken(errorMessage: String) {
		self.dict["errorMessage"] = errorMessage
	}
	
	public override func populate(_ dict: [String: Any]) throws {
		try super.populate(dict);
		// set members values:
		if dict["id"] != nil {
			id = Int64("\(dict["id"]!)")
		}
		if dict["createDate"] != nil {
			createDate = Int64("\(dict["createDate"]!)")
		}
		if dict["updateDate"] != nil {
			updateDate = Int64("\(dict["updateDate"]!)")
		}
		if dict["fileName"] != nil {
			fileName = dict["fileName"] as? String
		}
		if dict["status"] != nil {
			status = GenerateMetadataStatus(rawValue: "\(dict["status"]!)")
		}
		if dict["errorMessage"] != nil {
			errorMessage = dict["errorMessage"] as? String
		}

	}

}

